"""account trades

Revision ID: 0a2031fa0e82
Revises: bb1ff0a92536
Create Date: 2021-04-08 16:20:27.550171

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.schema import Sequence, DropSequence, CreateSequence
from sqlalchemy.orm import sessionmaker

# revision identifiers, used by Alembic.
revision = '0a2031fa0e82'
down_revision = 'bb1ff0a92536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(Sequence('account_trades_seq')))
    op.create_table('account_trades',
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('account_trades_seq')"), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('volume_buy', sa.Float(), nullable=False),
    sa.Column('volume_sell', sa.Float(), nullable=False),
    sa.Column('price_avg_buy', sa.Float(), nullable=False),
    sa.Column('price_avg_sell', sa.Float(), nullable=False),
    sa.Column('trades_count_buy', sa.Integer(), nullable=False),
    sa.Column('trades_count_sell', sa.Integer(), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_trades_name'), 'account_trades', ['name'], unique=False)
    op.create_index(op.f('ix_account_trades_symbol'), 'account_trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_account_trades_timestamp'), 'account_trades', ['timestamp'], unique=False)
    # ### end Alembic commands ###

    Session = sessionmaker()
    bind = op.get_bind()
    session = Session(bind=bind)

    session.execute(
        """
        SELECT create_hypertable('account_trades', 'timestamp', partitioning_column => 'symbol', number_partitions => 5, chunk_time_interval => interval '30 days');
        SELECT add_dimension('account_trades', 'name', number_partitions => 5);
        """
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_trades_timestamp'), table_name='account_trades')
    op.drop_index(op.f('ix_account_trades_symbol'), table_name='account_trades')
    op.drop_index(op.f('ix_account_trades_name'), table_name='account_trades')
    op.drop_table('account_trades')
    op.execute(DropSequence(Sequence('account_trades_seq')))
    # ### end Alembic commands ###
