"""Added account_trades.volume_base

Revision ID: 8db91ffd9c71
Revises: 2a0b9a52405f
Create Date: 2021-05-26 12:35:45.769609

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import sessionmaker

# revision identifiers, used by Alembic.
revision = '8db91ffd9c71'
down_revision = '2a0b9a52405f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    Session = sessionmaker()
    bind = op.get_bind()
    session = Session(bind=bind)
    session.execute(
        """
        DELETE FROM account_trades WHERE True=True;
        """
    )
    op.add_column('account_trades', sa.Column('volume_base_buy', sa.Float(), nullable=False))
    op.add_column('account_trades', sa.Column('volume_base_sell', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_trades', 'volume_base_sell')
    op.drop_column('account_trades', 'volume_base_buy')
    # ### end Alembic commands ###
