"""Added orderbook

Revision ID: cdef33152cd8
Revises: 0847beeaeefb
Create Date: 2021-12-24 15:12:59.567768

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.schema import Sequence, DropSequence, CreateSequence
from sqlalchemy.orm import sessionmaker

# revision identifiers, used by Alembic.
revision = 'cdef33152cd8'
down_revision = '0847beeaeefb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(Sequence('orderbook_seq')))
    op.create_table('orderbook',
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('orderbook_seq')"), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ts_l', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('channel', sa.String(length=500), nullable=False),
    sa.Column('b', sa.Numeric(precision=27, scale=18, asdecimal=False), nullable=False),
    sa.Column('a', sa.Numeric(precision=27, scale=18, asdecimal=False), nullable=False),
    sa.Column('b_a', sa.Numeric(precision=27, scale=18, asdecimal=False), nullable=False),
    sa.Column('a_a', sa.Numeric(precision=27, scale=18, asdecimal=False), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orderbook_channel'), 'orderbook', ['channel'], unique=False)
    # ### end Alembic commands ###
    Session = sessionmaker()
    bind = op.get_bind()
    session = Session(bind=bind)

    session.execute(
        """
        SELECT create_hypertable('orderbook', 'timestamp', partitioning_column => 'channel', number_partitions => 10, chunk_time_interval => interval '7 days');
        """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orderbook_channel'), table_name='orderbook')
    op.drop_table('orderbook')
    op.execute(DropSequence(Sequence('orderbook_seq')))
    # ### end Alembic commands ###
