"""Delete account trade

Revision ID: 077702574432
Revises: 0a2031fa0e82
Create Date: 2021-04-14 10:53:24.982249

"""
from alembic import op
from sqlalchemy.schema import Sequence, DropSequence

# revision identifiers, used by Alembic.
revision = '077702574432'
down_revision = '0a2031fa0e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('account_trades_symbol_timestamp_idx', table_name='account_trades')
    op.drop_index('ix_account_trades_name', table_name='account_trades')
    op.drop_index('ix_account_trades_symbol', table_name='account_trades')
    op.drop_index('ix_account_trades_timestamp', table_name='account_trades')
    op.drop_table('account_trades')
    op.execute(DropSequence(Sequence('account_trades_seq')))
    # ### end Alembic commands ###


def downgrade():
    pass
