"""Transfers sub account transfers

Revision ID: 60215ffa7a11
Revises: c1fd95f61a74
Create Date: 2021-08-19 16:18:45.246599

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.schema import Sequence, DropSequence, CreateSequence
from sqlalchemy.orm import sessionmaker



# revision identifiers, used by Alembic.
revision = '60215ffa7a11'
down_revision = 'c1fd95f61a74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    _downgrade()

    op.execute(CreateSequence(Sequence('transfers_seq')))
    op.create_table('transfers',
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('transfers_seq')"), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('transfer_type', sa.String(length=50), nullable=False),
    sa.Column('is_sub_account_transfer', sa.Boolean(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=27, scale=18, asdecimal=False), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=27, scale=18, asdecimal=False), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfers_name'), 'transfers', ['name'], unique=False)
    op.create_index(op.f('ix_transfers_symbol'), 'transfers', ['symbol'], unique=False)
    op.create_index(op.f('ix_transfers_transfer_type'), 'transfers', ['transfer_type'], unique=False)
    op.create_index(op.f('ix_transfers_is_sub_account_transfer'), 'transfers', ['is_sub_account_transfer'], unique=False)
    # ### end Alembic commands ###

    Session = sessionmaker()
    bind = op.get_bind()
    session = Session(bind=bind)

    session.execute(
        """
        SELECT create_hypertable('transfers', 'timestamp', partitioning_column => 'symbol', number_partitions => 5, chunk_time_interval => interval '30 days');
        SELECT add_dimension('transfers', 'transfer_type', number_partitions => 8);
        SELECT add_dimension('transfers', 'name', number_partitions => 5);
        SELECT add_dimension('transfers', 'is_sub_account_transfer', number_partitions => 2);
        """
    )


def _downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfers_transfer_type'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_symbol'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_name'), table_name='transfers')
    op.drop_table('transfers')
    # ### end Alembic commands ###
    op.execute(DropSequence(Sequence('transfers_seq')))


def downgrade():
    op.drop_index(op.f('ix_transfers_is_sub_account_transfer'), table_name='transfers')
    _downgrade()
