"""creates logs

Revision ID: b3bb18e6b182
Revises: 
Create Date: 2021-03-10 12:47:25.145155

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import sessionmaker

# revision identifiers, used by Alembic.
revision = 'b3bb18e6b182'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_performance_log_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('balance_base', sa.Float(), nullable=True),
    sa.Column('balance_quote', sa.Float(), nullable=True),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.Column('price_fair', sa.Float(), nullable=True),
    sa.Column('price_forex', sa.Float(), nullable=True),
    sa.Column('balance_base_borrowed', sa.Float(), nullable=True),
    sa.Column('balance_quote_borrowed', sa.Float(), nullable=True),
    # Timescale can't create tables with pk (except ts fields)
    # sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kalman_log_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('price_forex', sa.Float(), nullable=True),
    sa.Column('price_crypto', sa.Float(), nullable=True),
    sa.Column('ts_data', sa.Integer(), nullable=True),
    sa.Column('s1_x', sa.Float(), nullable=True),
    sa.Column('s1_P', sa.Float(), nullable=True),
    sa.Column('s2_x', sa.Float(), nullable=True),
    sa.Column('s2_P', sa.Float(), nullable=True),
    sa.Column('s3_x', sa.Float(), nullable=True),
    sa.Column('s3_P', sa.Float(), nullable=True),
    # Timescale can't create tables with pk (except ts fields)
    # sa.PrimaryKeyConstraint('id')
    )
    op.create_table('markets_data',
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('open', sa.Numeric(precision=22, scale=10), nullable=False),
    sa.Column('high', sa.Numeric(precision=22, scale=10), nullable=False),
    sa.Column('low', sa.Numeric(precision=22, scale=10), nullable=False),
    sa.Column('close', sa.Numeric(precision=22, scale=10), nullable=False),
    sa.Column('volume', sa.Numeric(precision=22, scale=10), nullable=False),
    sa.PrimaryKeyConstraint('timestamp', 'exchange', 'symbol')
    )
    # Create timescale tables
    Session = sessionmaker()
    bind = op.get_bind()
    session = Session(bind=bind)

    session.execute(
        "SELECT create_hypertable('bot_performance_log_entries', 'timestamp', chunk_time_interval => 86400);"
    )
    session.execute(
        "SELECT create_hypertable('kalman_log_entries', 'timestamp', chunk_time_interval => 86400);"
    )
    session.execute(
        "SELECT create_hypertable('markets_data', 'timestamp', partitioning_column => 'symbol', number_partitions => 10, chunk_time_interval => 86400);"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('markets_data')
    op.drop_table('kalman_log_entries')
    op.drop_table('bot_performance_log_entries')
    # ### end Alembic commands ###
