"""recreate rebate

Revision ID: 4787fac39004
Revises: 9ecc17859812
Create Date: 2021-06-19 00:08:48.870385

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.schema import Sequence, DropSequence, CreateSequence
from sqlalchemy.orm import sessionmaker

# revision identifiers, used by Alembic.
revision = '4787fac39004'
down_revision = '9ecc17859812'
branch_labels = None
depends_on = None


def _downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rebates_timestamp'), table_name='rebates')
    op.drop_index(op.f('ix_rebates_symbol'), table_name='rebates')
    op.drop_index(op.f('ix_rebates_name'), table_name='rebates')
    op.drop_index(op.f('ix_rebates_account_type'), table_name='rebates')
    op.drop_table('rebates')
    # ### end Alembic commands ###
    op.execute(DropSequence(Sequence('rebates_seq')))


def upgrade():
    _downgrade()
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(Sequence('rebates_seq')))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rebates',
        sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('rebates_seq')"), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('timestamp_received', sa.DateTime(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('symbol', sa.String(length=16), nullable=False),
        sa.Column('account_type', sa.String(length=50), nullable=False),
        sa.Column('rebate', sa.Float(), nullable=False),
        sa.Column('rebate_usd', sa.Float(), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rebates_account_type'), 'rebates', ['account_type'], unique=False)
    op.create_index(op.f('ix_rebates_name'), 'rebates', ['name'], unique=False)
    op.create_index(op.f('ix_rebates_symbol'), 'rebates', ['symbol'], unique=False)
    op.create_index(op.f('ix_rebates_timestamp'), 'rebates', ['timestamp'], unique=False)
    op.create_index(op.f('ix_rebates_timestamp_received'), 'rebates', ['timestamp_received'], unique=False)
    # ### end Alembic commands ###
    Session = sessionmaker()
    bind = op.get_bind()
    session = Session(bind=bind)

    session.execute(
        """
        SELECT create_hypertable('rebates', 'timestamp_received', partitioning_column => 'symbol', number_partitions => 5, chunk_time_interval => interval '30 days');
        SELECT add_dimension('rebates', 'timestamp', chunk_time_interval => INTERVAL '30 day');
        SELECT add_dimension('rebates', 'name', number_partitions => 5);
        SELECT add_dimension('rebates', 'account_type', number_partitions => 3);
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rebates_timestamp_received'), table_name='rebates')
    _downgrade()
    # ### end Alembic commands ###
