"""creates tables

Revision ID: 239c404e95cc
Revises: 
Create Date: 2021-03-16 09:24:08.768738

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.schema import Sequence, DropSequence, CreateSequence
from sqlalchemy.orm import sessionmaker

# revision identifiers, used by Alembic.
revision = '239c404e95cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute(CreateSequence(Sequence('bot_performance_log_entries_seq')))
    op.execute(CreateSequence(Sequence('kalman_log_entries_seq')))
    op.execute(CreateSequence(Sequence('markets_data_seq')))
    op.execute(CreateSequence(Sequence('price_indexes_seq')))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_performance_log_entries',
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('bot_performance_log_entries_seq')"), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('balance_base', sa.Float(), nullable=False),
    sa.Column('balance_quote', sa.Float(), nullable=False),
    sa.Column('bid', sa.Float(), nullable=False),
    sa.Column('ask', sa.Float(), nullable=False),
    sa.Column('price_fair', sa.Float(), nullable=False),
    sa.Column('price_forex', sa.Float(), nullable=False),
    sa.Column('balance_base_borrowed', sa.Float(), nullable=False),
    sa.Column('balance_quote_borrowed', sa.Float(), nullable=False),
    # Timescale can't create tables with pk (except ts fields)
    # sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_performance_log_entries_name'), 'bot_performance_log_entries', ['name'], unique=False)
    op.create_index(op.f('ix_bot_performance_log_entries_timestamp'), 'bot_performance_log_entries', ['timestamp'], unique=False)
    op.create_table('kalman_log_entries',
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('kalman_log_entries_seq')"), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('price_forex', sa.Float(), nullable=False),
    sa.Column('price_crypto', sa.Float(), nullable=False),
    sa.Column('ts_data', sa.Integer(), nullable=False),
    sa.Column('s1_x', sa.Float(), nullable=False),
    sa.Column('s1_P', sa.Float(), nullable=False),
    sa.Column('s2_x', sa.Float(), nullable=False),
    sa.Column('s2_P', sa.Float(), nullable=False),
    sa.Column('s3_x', sa.Float(), nullable=False),
    sa.Column('s3_P', sa.Float(), nullable=False),
    # Timescale can't create tables with pk (except ts fields)
    # sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kalman_log_entries_name'), 'kalman_log_entries', ['name'], unique=False)
    op.create_index(op.f('ix_kalman_log_entries_timestamp'), 'kalman_log_entries', ['timestamp'], unique=False)
    op.create_table('markets_data',
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('markets_data_seq')"), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('instrument', sa.Enum('SPOT', 'FUTURES', name='instrument', native_enum=False), nullable=False),
    sa.Column('open', sa.Numeric(precision=22, scale=10, asdecimal=False), nullable=False),
    sa.Column('high', sa.Numeric(precision=22, scale=10, asdecimal=False), nullable=False),
    sa.Column('low', sa.Numeric(precision=22, scale=10, asdecimal=False), nullable=False),
    sa.Column('close', sa.Numeric(precision=22, scale=10, asdecimal=False), nullable=False),
    sa.Column('volume', sa.Numeric(precision=22, scale=10, asdecimal=False), nullable=False),
    # Timescale can't create tables with pk (except ts fields)
    # sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_data_exchange'), 'markets_data', ['exchange'], unique=False)
    op.create_index(op.f('ix_markets_data_instrument'), 'markets_data', ['instrument'], unique=False)
    op.create_index(op.f('ix_markets_data_symbol'), 'markets_data', ['symbol'], unique=False)
    op.create_table('price_indexes',
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('price_indexes_seq')"), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=8, asdecimal=False), nullable=False),
    # Timescale can't create tables with pk (except ts fields)
    # sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_indexes_symbol'), 'price_indexes', ['symbol'], unique=False)

    # Create timescale tables
    Session = sessionmaker()
    bind = op.get_bind()
    session = Session(bind=bind)

    session.execute(
        """
        SELECT create_hypertable(
            'bot_performance_log_entries',
            'timestamp',
            partitioning_column => 'name',
            number_partitions => 5,
            chunk_time_interval => interval '30 days'
        );
        """
    )
    session.execute(
        """
        SELECT create_hypertable(
            'kalman_log_entries',
            'timestamp',
            partitioning_column => 'name',
            number_partitions => 5,
            chunk_time_interval => interval '30 days'
        );
        """
    )
    session.execute(
        """
        SELECT create_hypertable('markets_data', 'timestamp', partitioning_column => 'symbol', number_partitions => 5, chunk_time_interval => interval '30 days');
        SELECT add_dimension('markets_data', 'instrument', number_partitions => 4);
        SELECT add_dimension('markets_data', 'exchange', number_partitions => 5);
        """
    )

    session.execute(
        """
        SELECT create_hypertable(
            'price_indexes',
            'timestamp',
            partitioning_column => 'symbol',
            number_partitions => 5,
            chunk_time_interval => interval '30 days'
        );
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_indexes_symbol'), table_name='price_indexes')
    op.drop_table('price_indexes')
    op.drop_index(op.f('ix_markets_data_symbol'), table_name='markets_data')
    op.drop_index(op.f('ix_markets_data_instrument'), table_name='markets_data')
    op.drop_index(op.f('ix_markets_data_exchange'), table_name='markets_data')
    op.drop_table('markets_data')
    op.drop_index(op.f('ix_kalman_log_entries_timestamp'), table_name='kalman_log_entries')
    op.drop_index(op.f('ix_kalman_log_entries_name'), table_name='kalman_log_entries')
    op.drop_table('kalman_log_entries')
    op.drop_index(op.f('ix_bot_performance_log_entries_timestamp'), table_name='bot_performance_log_entries')
    op.drop_index(op.f('ix_bot_performance_log_entries_name'), table_name='bot_performance_log_entries')
    op.drop_table('bot_performance_log_entries')

    op.execute(DropSequence(Sequence('bot_performance_log_entries_seq')))
    op.execute(DropSequence(Sequence('kalman_log_entries_seq')))
    op.execute(DropSequence(Sequence('markets_data_seq')))
    op.execute(DropSequence(Sequence('price_indexes_seq')))
    # ### end Alembic commands ###
