"""rebates

Revision ID: 768b9e14cf59
Revises: 7733d3c12ff5
Create Date: 2021-05-06 17:19:16.576095

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.schema import Sequence, DropSequence, CreateSequence
from sqlalchemy.orm import sessionmaker

# revision identifiers, used by Alembic.
revision = '768b9e14cf59'
down_revision = '7733d3c12ff5'
branch_labels = None
depends_on = None


def upgrade():
    op.execute(CreateSequence(Sequence('rebates_seq')))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rebates',
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('rebates_seq')"), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('rebate', sa.Float(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rebates_account_type'), 'rebates', ['account_type'], unique=False)
    op.create_index(op.f('ix_rebates_name'), 'rebates', ['name'], unique=False)
    op.create_index(op.f('ix_rebates_symbol'), 'rebates', ['symbol'], unique=False)
    op.create_index(op.f('ix_rebates_timestamp'), 'rebates', ['timestamp'], unique=False)
    # ### end Alembic commands ###
    Session = sessionmaker()
    bind = op.get_bind()
    session = Session(bind=bind)

    session.execute(
        """
        SELECT create_hypertable('rebates', 'timestamp', partitioning_column => 'symbol', number_partitions => 5, chunk_time_interval => interval '30 days');
        SELECT add_dimension('rebates', 'name', number_partitions => 5);
        SELECT add_dimension('rebates', 'account_type', number_partitions => 3);
        """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rebates_timestamp'), table_name='rebates')
    op.drop_index(op.f('ix_rebates_symbol'), table_name='rebates')
    op.drop_index(op.f('ix_rebates_name'), table_name='rebates')
    op.drop_index(op.f('ix_rebates_account_type'), table_name='rebates')
    op.drop_table('rebates')
    # ### end Alembic commands ###
    op.execute(DropSequence(Sequence('rebates_seq')))
