"""creates logs

Revision ID: a82a1b20be88
Revises: 
Create Date: 2021-03-12 10:35:35.754288

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import sessionmaker
from sqlalchemy.schema import Sequence, CreateSequence, DropSequence


# revision identifiers, used by Alembic.
revision = 'a82a1b20be88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute(CreateSequence(Sequence('bot_performance_log_entries_seq')))
    op.execute(CreateSequence(Sequence('kalman_log_entries_seq')))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_performance_log_entries',
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('bot_performance_log_entries_seq')"), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('balance_base', sa.Float(), nullable=False),
    sa.Column('balance_quote', sa.Float(), nullable=False),
    sa.Column('bid', sa.Float(), nullable=False),
    sa.Column('ask', sa.Float(), nullable=False),
    sa.Column('price_fair', sa.Float(), nullable=False),
    sa.Column('price_forex', sa.Float(), nullable=False),
    sa.Column('balance_base_borrowed', sa.Float(), nullable=False),
    sa.Column('balance_quote_borrowed', sa.Float(), nullable=False),
    # Timescale can't create tables with pk (except ts fields)
    # sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_performance_log_entries_name'), 'bot_performance_log_entries', ['name'], unique=False)
    op.create_index(op.f('ix_bot_performance_log_entries_timestamp'), 'bot_performance_log_entries', ['timestamp'], unique=False)
    op.create_table('kalman_log_entries',
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('kalman_log_entries_seq')"), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('price_forex', sa.Float(), nullable=False),
    sa.Column('price_crypto', sa.Float(), nullable=False),
    sa.Column('ts_data', sa.Integer(), nullable=False),
    sa.Column('s1_x', sa.Float(), nullable=False),
    sa.Column('s1_P', sa.Float(), nullable=False),
    sa.Column('s2_x', sa.Float(), nullable=False),
    sa.Column('s2_P', sa.Float(), nullable=False),
    sa.Column('s3_x', sa.Float(), nullable=False),
    sa.Column('s3_P', sa.Float(), nullable=False),
    # Timescale can't create tables with pk (except ts fields)
    # sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kalman_log_entries_name'), 'kalman_log_entries', ['name'], unique=False)
    op.create_index(op.f('ix_kalman_log_entries_timestamp'), 'kalman_log_entries', ['timestamp'], unique=False)
    op.create_table('markets_data',
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('instrument', sa.Enum('spot', 'futures', name='instrument', native_enum=False), nullable=False),
    sa.Column('open', sa.Numeric(precision=22, scale=10, asdecimal=False), nullable=False),
    sa.Column('high', sa.Numeric(precision=22, scale=10, asdecimal=False), nullable=False),
    sa.Column('low', sa.Numeric(precision=22, scale=10, asdecimal=False), nullable=False),
    sa.Column('close', sa.Numeric(precision=22, scale=10, asdecimal=False), nullable=False),
    sa.Column('volume', sa.Numeric(precision=22, scale=10, asdecimal=False), nullable=False),
    sa.PrimaryKeyConstraint('timestamp', 'exchange', 'symbol', 'instrument')
    )

    # Create timescale tables
    Session = sessionmaker()
    bind = op.get_bind()
    session = Session(bind=bind)

    session.execute(
        """
        SELECT create_hypertable(
            'bot_performance_log_entries',
            'timestamp',
            partitioning_column => 'name',
            number_partitions => 10,
            chunk_time_interval => 86400
        );
        """
    )
    session.execute(
        """
        SELECT create_hypertable(
            'kalman_log_entries',
            'timestamp',
            partitioning_column => 'name',
            number_partitions => 10,
            chunk_time_interval => 86400
        );
        """
    )
    session.execute(
        """
        SELECT create_hypertable('markets_data', 'timestamp', partitioning_column => 'symbol', number_partitions => 10, chunk_time_interval => 86400);
        SELECT add_dimension('markets_data', 'instrument', number_partitions => 4);
        SELECT add_dimension('markets_data', 'exchange', number_partitions => 10);
        """
    )
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('markets_data')
    op.drop_index(op.f('ix_kalman_log_entries_timestamp'), table_name='kalman_log_entries')
    op.drop_index(op.f('ix_kalman_log_entries_name'), table_name='kalman_log_entries')
    op.drop_table('kalman_log_entries')
    op.drop_index(op.f('ix_bot_performance_log_entries_timestamp'), table_name='bot_performance_log_entries')
    op.drop_index(op.f('ix_bot_performance_log_entries_name'), table_name='bot_performance_log_entries')
    op.drop_table('bot_performance_log_entries')

    op.execute(DropSequence(Sequence('bot_performance_log_entries_seq')))
    op.execute(DropSequence(Sequence('kalman_log_entries_seq')))
    # ### end Alembic commands ###
