"""added price_crypto

Revision ID: bb1ff0a92536
Revises: 6e1e9dfa0d19
Create Date: 2021-03-24 13:19:09.500441

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb1ff0a92536'
down_revision = '6e1e9dfa0d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_performance_log_entries', sa.Column('price_crypto', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_performance_log_entries', 'price_crypto')
    # ### end Alembic commands ###
