"""Added bidask

Revision ID: 7eabcefcdd8b
Revises: bf219b8c56df
Create Date: 2021-06-14 14:23:48.826317

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.schema import Sequence, DropSequence, CreateSequence
from sqlalchemy.orm import sessionmaker

# revision identifiers, used by Alembic.
revision = '7eabcefcdd8b'
down_revision = 'bf219b8c56df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(Sequence('bid_ask_seq')))
    op.create_table('bid_ask',
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('bid_ask_seq')"), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('bid', sa.Numeric(precision=27, scale=18, asdecimal=False), nullable=False),
    sa.Column('ask', sa.Numeric(precision=27, scale=18, asdecimal=False), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_ask_account_type'), 'bid_ask', ['account_type'], unique=False)
    op.create_index(op.f('ix_bid_ask_exchange'), 'bid_ask', ['exchange'], unique=False)
    op.create_index(op.f('ix_bid_ask_symbol'), 'bid_ask', ['symbol'], unique=False)
    # ### end Alembic commands ###
    Session = sessionmaker()
    bind = op.get_bind()
    session = Session(bind=bind)

    session.execute(
        """
        SELECT create_hypertable('bid_ask', 'timestamp', partitioning_column => 'symbol', number_partitions => 5, chunk_time_interval => interval '7 days');
        SELECT add_dimension('bid_ask', 'account_type', number_partitions => 5);
        SELECT add_dimension('bid_ask', 'exchange', number_partitions => 5);
        """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bid_ask_symbol'), table_name='bid_ask')
    op.drop_index(op.f('ix_bid_ask_exchange'), table_name='bid_ask')
    op.drop_index(op.f('ix_bid_ask_account_type'), table_name='bid_ask')
    op.drop_table('bid_ask')
    op.execute(DropSequence(Sequence('bid_ask_seq')))
    # ### end Alembic commands ###
