"""add account_trades to markets data

Revision ID: bf219b8c56df
Revises: 8db91ffd9c71
Create Date: 2021-06-09 12:15:58.861711

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf219b8c56df'
down_revision = '8db91ffd9c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets_data', sa.Column('account_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markets_data', 'account_type')
    # ### end Alembic commands ###
