"""Added bswap_quote

Revision ID: 0847beeaeefb
Revises: 60215ffa7a11
Create Date: 2021-11-26 14:00:17.874171

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.schema import Sequence, DropSequence, CreateSequence
from sqlalchemy.orm import sessionmaker

# revision identifiers, used by Alembic.
revision = '0847beeaeefb'
down_revision = '60215ffa7a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(Sequence('bswap_quote_seq')))
    op.create_table('bswap_quote',
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('bswap_quote_seq')"), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=27, scale=18, asdecimal=False), nullable=False),
    sa.Column('slippage', sa.Numeric(precision=27, scale=18, asdecimal=False), nullable=False),
    sa.Column('fee', sa.Numeric(precision=27, scale=18, asdecimal=False), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bswap_quote_symbol'), 'bswap_quote', ['symbol'], unique=False)
    # ### end Alembic commands ###
    Session = sessionmaker()
    bind = op.get_bind()
    session = Session(bind=bind)

    session.execute(
        """
        SELECT create_hypertable('bswap_quote', 'timestamp', partitioning_column => 'symbol', number_partitions => 5, chunk_time_interval => interval '7 days');
        """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bswap_quote_symbol'), table_name='bswap_quote')
    op.drop_table('bswap_quote')
    op.execute(DropSequence(Sequence('bswap_quote_seq')))
    # ### end Alembic commands ###
