"""replace BotPerfomance.name with bot_id

Revision ID: 6e1e9dfa0d19
Revises: 94682836261c
Create Date: 2021-03-24 12:19:35.290212

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.schema import Sequence, DropSequence, CreateSequence
from sqlalchemy.orm import sessionmaker

# revision identifiers, used by Alembic.
revision = '6e1e9dfa0d19'
down_revision = '94682836261c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_performance_log_entries_name'), table_name='bot_performance_log_entries')
    op.drop_table('bot_performance_log_entries')

    op.execute(DropSequence(Sequence('bot_performance_log_entries_seq')))
    op.execute(CreateSequence(Sequence('bot_performance_log_entries_seq')))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_performance_log_entries',
    sa.Column('id', sa.BigInteger(),
              server_default=sa.text("nextval('bot_performance_log_entries_seq')"), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('balance_base', sa.Float(), nullable=False),
    sa.Column('balance_quote', sa.Float(), nullable=False),
    sa.Column('bid', sa.Float(), nullable=False),
    sa.Column('ask', sa.Float(), nullable=False),
    sa.Column('price_fair', sa.Float(), nullable=False),
    sa.Column('price_forex', sa.Float(), nullable=False),
    sa.Column('balance_base_borrowed', sa.Float(), nullable=False),
    sa.Column('balance_quote_borrowed', sa.Float(), nullable=False),
    # Timescale can't create tables with pk (except ts fields)
    # sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_performance_log_entries_bot_id'), 'bot_performance_log_entries', ['bot_id'], unique=False)

    # Create timescale tables
    Session = sessionmaker()
    bind = op.get_bind()
    session = Session(bind=bind)

    session.execute(
        """
        SELECT create_hypertable(
            'bot_performance_log_entries',
            'timestamp',
            partitioning_column => 'bot_id',
            number_partitions => 5,
            chunk_time_interval => interval '30 days'
        );
        """
    )
    # ### end Alembic commands ###


def downgrade():
    pass
