"""added balance

Revision ID: 9ecc17859812
Revises: 7eabcefcdd8b
Create Date: 2021-06-17 16:36:46.843588

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.schema import Sequence, DropSequence, CreateSequence
from sqlalchemy.orm import sessionmaker

# revision identifiers, used by Alembic.
revision = '9ecc17859812'
down_revision = '7eabcefcdd8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(Sequence('balances_seq')))
    op.create_table('balances',
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('balances_seq')"), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=27, scale=18, asdecimal=False), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=27, scale=18, asdecimal=False), nullable=False),
    sa.Column('borrowed', sa.Numeric(precision=27, scale=18, asdecimal=False), nullable=False),
    sa.Column('borrowed_usd', sa.Numeric(precision=27, scale=18, asdecimal=False), nullable=False),
    sa.Column('interest', sa.Numeric(precision=27, scale=18, asdecimal=False), nullable=False),
    sa.Column('interest_usd', sa.Numeric(precision=27, scale=18, asdecimal=False), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balances_account_type'), 'balances', ['account_type'], unique=False)
    op.create_index(op.f('ix_balances_symbol'), 'balances', ['symbol'], unique=False)
    op.create_index(op.f('ix_balances_name'), 'balances', ['name'], unique=False)
    # ### end Alembic commands ###
    Session = sessionmaker()
    bind = op.get_bind()
    session = Session(bind=bind)

    session.execute(
        """
        SELECT create_hypertable('balances', 'timestamp', partitioning_column => 'symbol', number_partitions => 5, chunk_time_interval => interval '7 days');
        SELECT add_dimension('balances', 'account_type', number_partitions => 5);
        SELECT add_dimension('balances', 'name', number_partitions => 5);
        """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_balances_symbol'), table_name='balances')
    op.drop_index(op.f('ix_balances_account_type'), table_name='balances')
    op.drop_index(op.f('ix_balances_name'), table_name='balances')
    op.drop_table('balances')
    op.execute(DropSequence(Sequence('balances_seq')))
    # ### end Alembic commands ###
