"""Added kalman_log

Revision ID: 105c35a288c7
Revises: cdef33152cd8
Create Date: 2021-12-24 15:31:10.117622

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.schema import Sequence, DropSequence, CreateSequence
from sqlalchemy.orm import sessionmaker

# revision identifiers, used by Alembic.
revision = '105c35a288c7'
down_revision = 'cdef33152cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(Sequence('kalman_log_seq')))
    op.create_table('kalman_log',
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('kalman_log_seq')"), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('channel', sa.String(length=500), nullable=False),
    sa.Column('brt', sa.Numeric(precision=27, scale=18, asdecimal=False), nullable=False),
    sa.Column('art', sa.Numeric(precision=27, scale=18, asdecimal=False), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kalman_log_channel'), 'kalman_log', ['channel'], unique=False)
    # ### end Alembic commands ###
    Session = sessionmaker()
    bind = op.get_bind()
    session = Session(bind=bind)

    session.execute(
        """
        SELECT create_hypertable('kalman_log', 'timestamp', partitioning_column => 'channel', number_partitions => 10, chunk_time_interval => interval '7 days');
        """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kalman_log_channel'), table_name='kalman_log')
    op.drop_table('kalman_log')
    op.execute(DropSequence(Sequence('kalman_log_seq')))
    # ### end Alembic commands ###
