"""Added price index

Revision ID: dd981adb2689
Revises: a82a1b20be88
Create Date: 2021-03-15 13:02:38.490310

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import sessionmaker

# revision identifiers, used by Alembic.
revision = 'dd981adb2689'
down_revision = 'a82a1b20be88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_indexes',
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=8, asdecimal=False), nullable=False),
    sa.PrimaryKeyConstraint('timestamp', 'symbol')
    )

    # Create timescale tables
    Session = sessionmaker()
    bind = op.get_bind()
    session = Session(bind=bind)

    session.execute(
        """
        SELECT create_hypertable(
            'price_indexes',
            'timestamp',
            partitioning_column => 'symbol',
            number_partitions => 10,
            chunk_time_interval => 86400
        );
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_indexes')
    # ### end Alembic commands ###
