"""kalman longer name

Revision ID: 2a0b9a52405f
Revises: d57dfbba4391
Create Date: 2021-05-12 15:19:08.726203

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.schema import Sequence, DropSequence, CreateSequence
from sqlalchemy.orm import sessionmaker


# revision identifiers, used by Alembic.
revision = '2a0b9a52405f'
down_revision = 'd57dfbba4391'
branch_labels = None
depends_on = None


def upgrade():
    downgrade()
    op.execute(CreateSequence(Sequence('kalman_log_entries_seq')))
    op.create_table('kalman_log_entries',
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('kalman_log_entries_seq')"),
              nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.Column('price_forex', sa.Float(), nullable=False),
    sa.Column('price_crypto', sa.Float(), nullable=False),
    sa.Column('ts_data', sa.Integer(), nullable=False),
    sa.Column('s1_x', sa.Float(), nullable=False),
    sa.Column('s1_P', sa.Float(), nullable=False),
    sa.Column('s2_x', sa.Float(), nullable=False),
    sa.Column('s2_P', sa.Float(), nullable=False),
    sa.Column('s3_x', sa.Float(), nullable=False),
    sa.Column('s3_P', sa.Float(), nullable=False),
    # Timescale can't create tables with pk (except ts fields)
    # sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kalman_log_entries_name'), 'kalman_log_entries', ['name'], unique=False)
    op.create_index(op.f('ix_kalman_log_entries_timestamp'), 'kalman_log_entries', ['timestamp'], unique=False)

    Session = sessionmaker()
    bind = op.get_bind()
    session = Session(bind=bind)
    session.execute(
        """
        SELECT create_hypertable(
            'kalman_log_entries',
            'timestamp',
            partitioning_column => 'name',
            number_partitions => 5,
            chunk_time_interval => interval '30 days'
        );
        """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kalman_log_entries_timestamp'), table_name='kalman_log_entries')
    op.drop_index(op.f('ix_kalman_log_entries_name'), table_name='kalman_log_entries')
    op.drop_table('kalman_log_entries')

    op.execute(DropSequence(Sequence('kalman_log_entries_seq')))
    # ### end Alembic commands ###
