"""added free

Revision ID: 9b285391a054
Revises: 1f7387d814ed
Create Date: 2022-03-03 17:34:41.511920

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b285391a054'
down_revision = '1f7387d814ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balances', sa.Column('free', sa.Numeric(precision=27, scale=18, asdecimal=False), nullable=True))
    op.add_column('balances', sa.Column('free_usd', sa.Numeric(precision=27, scale=18, asdecimal=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balances', 'free_usd')
    op.drop_column('balances', 'free')
    # ### end Alembic commands ###
