"""Added trades_log

Revision ID: 4af99cc42093
Revises: 105c35a288c7
Create Date: 2022-01-21 22:34:20.740771

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.schema import Sequence, DropSequence, CreateSequence
from sqlalchemy.orm import sessionmaker

# revision identifiers, used by Alembic.
revision = '4af99cc42093'
down_revision = '105c35a288c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(Sequence('trade_log_seq')))
    op.create_table('trade_log',
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('trade_log_seq')"), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ts_end', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('swap_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=500), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_log_channel'), 'trade_log', ['channel'], unique=False)
    # ### end Alembic commands ###
    Session = sessionmaker()
    bind = op.get_bind()
    session = Session(bind=bind)

    session.execute(
        """
        SELECT create_hypertable('trade_log', 'timestamp', partitioning_column => 'channel', number_partitions => 10, chunk_time_interval => interval '7 days');
        """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_log_channel'), table_name='trade_log')
    op.drop_table('trade_log')
    op.execute(DropSequence(Sequence('trade_log_seq')))
    # ### end Alembic commands ###
