"""added tickers

Revision ID: 1f7387d814ed
Revises: 4af99cc42093
Create Date: 2022-02-10 18:29:16.188340

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.schema import Sequence, DropSequence, CreateSequence
from sqlalchemy.orm import sessionmaker

# revision identifiers, used by Alembic.
revision = '1f7387d814ed'
down_revision = '4af99cc42093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(Sequence('ticker_seq')))
    op.create_table('ticker',
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('ticker_seq')"), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('channel', sa.String(length=500), nullable=False),
    sa.Column('p', sa.Numeric(precision=27, scale=18, asdecimal=False), nullable=False),
    sa.Column('q', sa.Numeric(precision=27, scale=18, asdecimal=False), nullable=False),
    sa.Column('bm', sa.Boolean(), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticker_channel'), 'ticker', ['channel'], unique=False)
    # ### end Alembic commands ###
    Session = sessionmaker()
    bind = op.get_bind()
    session = Session(bind=bind)

    session.execute(
        """
        SELECT create_hypertable('ticker', 'timestamp', partitioning_column => 'channel', number_partitions => 10, chunk_time_interval => interval '7 days');
        """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticker_channel'), table_name='ticker')
    op.drop_table('ticker')
    op.execute(DropSequence(Sequence('ticker_seq')))
    # ### end Alembic commands ###
