"""Unclaimed bnb

Revision ID: 8dfab127ae50
Revises: 9b285391a054
Create Date: 2022-03-07 18:34:12.441982

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.schema import Sequence, DropSequence, CreateSequence
from sqlalchemy.orm import sessionmaker

# revision identifiers, used by Alembic.
revision = '8dfab127ae50'
down_revision = '9b285391a054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(Sequence('unclaimed_bnb_seq')))
    op.create_table('unclaimed_bnb',
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('unclaimed_bnb_seq')"), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unclaimed', sa.Numeric(precision=27, scale=18, asdecimal=False), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unclaimed_bnb_name'), 'unclaimed_bnb', ['name'], unique=False)
    # ### end Alembic commands ###

    Session = sessionmaker()
    bind = op.get_bind()
    session = Session(bind=bind)

    session.execute(
        """
        SELECT create_hypertable('unclaimed_bnb', 'timestamp', partitioning_column => 'name', number_partitions => 10, chunk_time_interval => interval '7 days');
        """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unclaimed_bnb_name'), table_name='unclaimed_bnb')
    op.drop_table('unclaimed_bnb')
    op.execute(DropSequence(Sequence('unclaimed_bnb_seq')))
    # ### end Alembic commands ###
