name: Deploy

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('requirements.txt') }}

    - name: Install dependencies
      run: |
        pip3 install awscli docker-compose

    - name: Build & push images
      env:
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      run: |
        docker-compose build app nginx
        aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
        aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }}  | docker login --username AWS --password-stdin ${{ secrets.DOCKER_REGISTRY }}
        docker-compose push app nginx

    - name: Copy files via SCP
      uses: appleboy/scp-action@master
      env:
        KEY: ${{ secrets.SSH_KEY }}
        HOST: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USER }}
      with:
        source: "*"
        target: "/home/ubuntu/datastore"

    - name: Up app
      uses: appleboy/ssh-action@master
      env:
        KEY: ${{ secrets.SSH_KEY }}
        HOST: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USER }}
      with:
        script: |
          cd /home/ubuntu/datastore && \
          echo "dir changed" && \
          chmod +x deploy.sh && \
          ./deploy.sh --migrate
